# Default values for nestedkube.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

mode: minikube

# Set a path on the docker host to enable caching of kubernetes images
baseCachePath:
