apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" . }}-master"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ template "fullname" . }}-master"
    spec:
      containers:
        - name: "{{ template "fullname" . }}-master"
          image: maru/nkube
          imagePullPolicy: IfNotPresent
          ports:
            - name: kubernetes-api
              containerPort: 443
            - name: discovery
              containerPort: 9898
          securityContext:
            privileged: true
          volumeMounts:
          - name: secret
            mountPath: /etc/nkube/secret
            readOnly: true
          - name: config
            mountPath: /etc/nkube/config
            readOnly: true
          {{- if .Values.baseCachePath }}
          - name: cache
            mountPath: /nkube-cache
          {{- end }}
      volumes:
        - name: secret
          secret:
            secretName: {{ template "fullname" . }}
        - name: config
          configMap:
            name: {{ template "fullname" . }}
        {{- if .Values.baseCachePath }}
        - name: cache
          hostPath:
            path: {{ .Values.baseCachePath }}
        {{- end }}
